name: Say hello

on:
  push:
    branches:
      - personal-test

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "Hola Sergio!"
      - run: ls -l
      - run: date