name: Deployment Pipeline

on:
  push:
    branches: [personal-test]
  pull_request:
    branches: [personal-test]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: install cypress@8.2.0
        run: npm install -D cypress@8.2.0
      - name: E2E test
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000
      - name: Deploy
        if: ${{ github.event_name }} == 'push'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "https://${{secrets.HEROKU_APP}}.herokuapp.com/health"
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          healthcheck: http://localhost:5000/health
          rollbackonhealthcheckfailed: true
